In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('brutes/donnees_socio_economiques.csv')
df1.head()

,code_insee_com,nom_com,niveau_vie_median_2021,nb_logements_2022,Pourcentage_appartements_2022,pourcentage_locataires_dans_résidence_principale_2022,evolution_annuelle_moy_de_la_population_entre_2017_et_2023_en_pourcentage,population_municipale_2023,Taux_activite_tranche_15_64_en_2022
0,1001,L'Abergement-Clémenciat,25820,379,2.4,13.8,1.73,860,82.1
1,1002,L'Abergement-de-Varey,24480,175,1.1,9.9,1.43,270,80.1
2,1004,Ambérieu-en-Bugey,21660,7973,54.1,53.1,2.14,15934,76.7
3,1005,Ambérieux-en-Dombes,24610,921,26.5,25.2,2.03,1906,81.3
4,1006,Ambléon,24210,71,4.2,26.3,0.59,115,70.8

In [3]:
df2 = pd.read_csv('brutes/donnees_geo_climatiques.csv')
df2.head()

/tmp/ipykernel_158393/960960266.py:1: DtypeWarning: Columns (0: code_insee_com, 1: dep_code) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv('brutes/donnees_geo_climatiques.csv')

,code_insee_com,nom_com,reg_code,reg_nom,dep_code,dep_nom,population,superficie_km2,densite,latitude,...,RR_med,NBJRR1_med,NBJRR5_med,NBJRR10_med,Tmin_med,Tmax_med,Tens_vap_med,Force_vent_med,Insolation_med,Rayonnement_med
0,1001,Abergement-Clémenciat,84,Auvergne-Rhône-Alpes,1,Ain,832,16,53.0,46.153,...,66.00,10.0,4.0,2.0,7.05,17.1,10.35,2.6,3059.0,12079.0
1,1002,Abergement-de-Varey,84,Auvergne-Rhône-Alpes,1,Ain,267,9,29.0,46.009,...,104.80,10.0,6.0,4.0,6.60,17.6,10.75,1.1,2934.0,11543.5
2,1004,Ambérieu-en-Bugey,84,Auvergne-Rhône-Alpes,1,Ain,14854,24,607.0,45.961,...,86.85,10.0,5.0,3.0,6.30,16.6,10.15,2.5,2934.0,11543.5
3,1005,Ambérieux-en-Dombes,84,Auvergne-Rhône-Alpes,1,Ain,1897,16,118.0,45.996,...,63.80,9.0,4.0,2.0,7.05,17.1,10.40,1.8,2314.0,NaN
4,1006,Ambléon,84,Auvergne-Rhône-Alpes,1,Ain,113,6,19.0,45.750,...,89.80,9.0,5.0,3.0,7.30,17.5,10.30,1.8,3314.0,13004.0

In [4]:
df3 = pd.read_csv('brutes/mesures_occitanie_journaliere_pollution.csv')
df3.head()

,nom_dept,nom_com,code_insee_com,nom_station,code_station,typologie,influence,nom_poll,valeur_poll,jour,mois,annee
0,TARN-ET-GARONNE,MONTAUBAN,82121,Montauban - Ramierou Urbain,FR50060,Urbaine,Fond,NOX,12.7,8,1,2023
1,TARN-ET-GARONNE,MONTAUBAN,82121,Montauban - Ramierou Urbain,FR50060,Urbaine,Fond,NOX,9.9,9,1,2023
2,TARN-ET-GARONNE,MONTAUBAN,82121,Montauban - Ramierou Urbain,FR50060,Urbaine,Fond,NOX,39.1,11,1,2023
3,TARN-ET-GARONNE,MONTAUBAN,82121,Montauban - Ramierou Urbain,FR50060,Urbaine,Fond,NOX,68.6,12,1,2023
4,TARN-ET-GARONNE,MONTAUBAN,82121,Montauban - Ramierou Urbain,FR50060,Urbaine,Fond,NOX,41.8,13,1,2023

In [7]:
%%sql
SELECT ROUND(MEDIAN(valeur_poll), 2) AS valeur_poll_med, ROUND(AVG(valeur_poll), 2) AS valeur_poll_avg, *
FROM UE403_SOCIO_ECONOMIQUES SE
INNER JOIN UE403_GEO_CLIMATIQUES GC USING (code_insee_com)
INNER JOIN UE403_MESURES_JOURNALIERE_POLLUTION USING (code_insee_com)
GROUP BY code_insee_com;

,valeur_poll_med,valeur_poll_avg,niveau_vie_median_2021,nb_logements_2022,Pourcentage_appartements_2022,pourcentage_locataires_dans_résidence_principale_2022,evolution_annuelle_moy_de_la_population_entre_2017_et_2023_en_pourcentage,population_municipale_2023,Taux_activite_tranche_15_64_en_2022,code_insee_com,...,Insolation_med,Rayonnement_med,jour,mois,annee,typologie,influence,nom_poll,valeur_poll,code_station
0,9.90,22.00,22210,16749,81.9,54.0,-0.05,23981,72.1,12202,...,3672.5,13495.0,1,1,2023,Urbaine,Fond,NO,1.10,FR50815
1,10.00,15.45,18000,25704,62.5,59.2,2.31,46125,62.8,30007,...,3865.5,13845.0,1,1,2024,Urbaine,Fond,NO,2.50,FR50801
2,54.15,51.60,21630,1227,15.9,36.4,2.85,2604,76.1,30061,...,4324.5,14620.0,1,1,2024,Périurbaine,Fond,O3,36.50,FR50213
3,12.90,19.17,18760,86696,69.5,57.4,0.14,151839,66.4,30189,...,4324.5,14620.0,1,1,2023,Urbaine,Fond,NO,0.80,FR50211
4,61.50,59.70,24560,1037,13.9,23.5,0.48,2096,80.0,30315,...,4377.0,14986.0,1,1,2023,Rurale proche Zone Urbaine,Industrielle,O3,46.60,FR50216
5,62.90,64.09,22770,56,0.0,9.8,-0.15,114,81.5,31060,...,3605.0,15422.0,1,1,2023,Rurale Régionale,Fond,O3,62.20,FR50031
6,10.90,12.24,23110,1917,21.0,31.3,0.95,4310,81.3,31066,...,3239.5,12941.5,1,1,2023,Rurale proche Zone Urbaine,Industrielle,PM10,20.80,FR50047
7,10.90,14.70,25350,14478,68.4,53.1,2.00,27604,80.3,31069,...,3378.0,12998.5,1,1,2023,Périurbaine,Trafic,NO,1.40,FR50043
8,0.90,9.62,20040,452,10.6,24.7,-0.96,736,71.4,31344,...,3884.0,14003.0,1,1,2023,Urbaine,Industrielle,H2S,3.70,FR50015
9,37.90,36.14,27200,1153,12.2,19.5,1.05,2587,82.4,31381,...,3982.0,14329.5,1,1,2023,Périurbaine,Fond,NO2,1.90,FR50041
10,0.40,0.63,19530,7263,49.4,48.7,0.88,12139,70.1,31483,...,3373.0,13106.5,1,1,2023,Urbaine,Industrielle,H2S,1.20,FR50016
11,17.40,30.01,22140,318683,83.8,65.8,1.19,514819,71.8,31555,...,3378.0,12998.5,1,1,2023,Urbaine,Fond,NO,0.80,FR50030
12,12.60,21.18,21800,13843,53.4,54.4,0.37,22428,71.4,32013,...,3218.0,12922.0,1,1,2023,Urbaine,Fond,NO,3.40,FR50833
13,64.20,64.42,N/A - secret statistique,62,1.5,18.0,-1.56,101,71.2,32139,...,3522.0,13471.0,1,1,2023,Rurale Régionale,Fond,O3,56.30,FR50029
14,2.70,15.92,N/A - secret statistique,48,2.1,19.4,-1.74,63,75.6,32317,...,3343.0,12575.0,1,1,2023,Rurale Nationale,Fond,NO,0.13,FR50020
15,7.10,22.65,20410,50239,72.2,42.0,0.76,29939,68.7,34003,...,4530.5,15158.5,1,1,2023,Périurbaine,Fond,NO,0.60,FR50210
16,14.90,20.63,16830,48370,63.3,58.0,0.92,81545,63.4,34032,...,4299.0,14539.5,1,1,2023,Urbaine,Trafic,NO,2.40,FR50226
17,66.00,65.52,22500,856,9.9,22.1,-0.94,1622,74.0,34084,...,4299.0,14539.5,1,1,2023,Rurale Régionale,Fond,O3,69.40,FR50209
18,62.85,60.32,26460,9366,50.7,38.3,0.78,17351,79.1,34129,...,4690.0,15794.0,1,1,2024,Périurbaine,Fond,O3,62.50,FR50205
19,7.40,8.95,21680,1983,19.2,33.7,2.30,4507,78.4,34146,...,4205.0,15149.0,1,1,2023,Périurbaine,Industrielle,NO,0.40,FR50206
20,20.50,34.35,19670,184054,86.9,66.7,1.42,310240,67.1,34172,...,4690.0,15794.0,1,1,2023,Urbaine,Fond,NO,0.50,FR50201
21,65.35,63.89,29940,4629,17.4,23.3,1.12,10472,75.6,34255,...,4690.0,15794.0,1,1,2023,Périurbaine,Fond,O3,67.90,FR50204
22,14.60,17.61,19960,33474,81.9,51.8,0.80,45337,67.4,34301,...,4104.0,14498.0,1,1,2025,Urbaine,Trafic,NO2,23.50,FR50228
23,8.80,10.35,20730,1180,23.3,40.5,-1.47,1957,77.2,46029,...,NaN,NaN,1,1,2026,Urbaine,Fond,PM10,34.90,FR50066
24,5.20,6.55,22980,7263,59.4,51.8,0.45,12464,74.2,48095,...,3506.5,12843.0,1,1,2025,Urbaine,Fond,PM10,16.10,FR50231
25,14.70,22.32,21770,2418,55.8,40.8,-0.82,2761,74.2,65025,...,3156.0,12814.0,1,1,2023,Urbaine,Fond,NO,3.50,FR50813
26,5.30,5.83,22430,196,5.7,17.1,-1.33,347,75.3,65159,...,3276.0,13039.0,1,1,2026,Périurbaine,Industrielle,NO,1.30,FR50837
27,9.10,19.28,18810,9910,65.3,49.6,-0.15,13266,68.9,65286,...,3156.0,12814.0,1,1,2023,Urbaine,Fond,NO,3.40,FR50042
28,12.30,21.02,19070,30401,75.3,64.0,1.12,44399,64.8,65440,...,3156.0,12814.0,1,1,2023,Urbaine,Fond,NO,4.40,FR50052
29,4.60,7.23,23310,3508,50.8,30.3,0.16,816,76.9,66020,...,4173.0,15741.0,1,1,2025,Rurale Régionale,Fond,PM10,15.80,FR50802
30,28.80,37.79,17380,74540,73.2,56.9,0.20,121616,62.9,66136,...,4099.0,14633.5,1,1,2023,Urbaine,Fond,NO2,22.00,FR50220
31,67.80,66.47,22170,5925,28.1,31.2,-0.04,11630,74.4,66172,...,4099.0,14633.5,1,1,2023,Périurbaine,Fond,O3,22.80,FR50221
32,8.20,10.35,21650,30811,49.7,52.3,0.77,51290,68.1,81004,...,3511.5,13241.5,1,1,2023,Urbaine,Fond,NO,2.10,FR50026
33,7.60,19.00,20940,24061,40.1,43.4,0.34,42505,72.0,81065,...,3031.0,12325.5,1,1,2023,Urbaine,Fond,NO,0.60,FR50053
34,13.40,22.26,21630,33070,44.0,43.5,0.58,62945,72.7,82121,...,3433.0,13247.0,1,1,2023,Urbaine,Fond,NO,2.50,FR50060
35,12.20,23.17,20320,4482,42.6,45.7,-1.00,6008,74.3,9261,...,3208.5,12950.0,1,1,2023,Urbaine,Fond,NO,2.10,FR50826

In [8]:
df_sql1.head()

,valeur_poll_med,valeur_poll_avg,niveau_vie_median_2021,nb_logements_2022,Pourcentage_appartements_2022,pourcentage_locataires_dans_résidence_principale_2022,evolution_annuelle_moy_de_la_population_entre_2017_et_2023_en_pourcentage,population_municipale_2023,Taux_activite_tranche_15_64_en_2022,code_insee_com,...,Insolation_med,Rayonnement_med,jour,mois,annee,typologie,influence,nom_poll,valeur_poll,code_station
0,9.90,22.00,22210,16749,81.9,54.0,-0.05,23981,72.1,12202,...,3672.5,13495.0,1,1,2023,Urbaine,Fond,NO,1.1,FR50815
1,10.00,15.45,18000,25704,62.5,59.2,2.31,46125,62.8,30007,...,3865.5,13845.0,1,1,2024,Urbaine,Fond,NO,2.5,FR50801
2,54.15,51.60,21630,1227,15.9,36.4,2.85,2604,76.1,30061,...,4324.5,14620.0,1,1,2024,Périurbaine,Fond,O3,36.5,FR50213
3,12.90,19.17,18760,86696,69.5,57.4,0.14,151839,66.4,30189,...,4324.5,14620.0,1,1,2023,Urbaine,Fond,NO,0.8,FR50211
4,61.50,59.70,24560,1037,13.9,23.5,0.48,2096,80.0,30315,...,4377.0,14986.0,1,1,2023,Rurale proche Zone Urbaine,Industrielle,O3,46.6,FR50216

In [11]:
df_sql1.select_dtypes(include=['float', 'int']).columns

Index(['valeur_poll_med', 'valeur_poll_avg', 'nb_logements_2022',
       'Pourcentage_appartements_2022',
       'pourcentage_locataires_dans_résidence_principale_2022',
       'evolution_annuelle_moy_de_la_population_entre_2017_et_2023_en_pourcentage',
       'population_municipale_2023', 'Taux_activite_tranche_15_64_en_2022',
       'code_insee_com', 'population', 'superficie_km2', 'densite', 'latitude',
       'longitude', 'alti_med', 'RR_med', 'NBJRR1_med', 'NBJRR5_med',
       'NBJRR10_med', 'Tmin_med', 'Tmax_med', 'Tens_vap_med', 'Force_vent_med',
       'Insolation_med', 'Rayonnement_med', 'jour', 'mois', 'annee',
       'valeur_poll'],
      dtype='str')